name: nas_deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: 그래이들 퍼미션 부여
        run: chmod +x ./gradlew

      - name: application.yml 생성
        run: echo "${{ secrets.SPRING_YML }}" > ./src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker Image
        run: |
          docker build --platform linux/arm64/v8 -t paradoxlover9417/sansocialmedia:latest .
          echo "DOCKER_IMAGE=paradoxlover9417/sansocialmedia:latest" >> $GITHUB_ENV

      - name: Sign in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}

      - name: Deploy to NAS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            export PATH=$PATH:/usr/local/bin
            export PW=${{ secrets.NAS_PASSWORD }}
            echo $PW | sudo -S docker pull paradoxlover9417/sansocialmedia:latest
            echo $PW | sudo -S docker stop sansocialmedia || true
            echo $PW | sudo -S docker rm sansocialmedia || true
            echo $PW | sudo -S docker run -d -p 8080:8080 --name sansocialmedia paradoxlover9417/sansocialmedia:latest
          


